spring.application.name: employee-api
server.port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeeManagement
    username: root
    password: Yash@2000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  logging:
    level:
      root: INFO
      com.reliaquest.api: DEBUG
